use_frameworks!

platform :ios, '9.0'

target 'CRJUIComponents_Example' do
  pod 'CRJUIComponents', :path => '../'
#  pod 'CRJCategories', '0.1.3'
#  pod 'CRJGeneralTools'
  target 'CRJUIComponents_Tests' do
    inherit! :search_paths

    
  end
end
