use_frameworks!

platform :ios, '8.0'

target 'CRJUIComponents_Example' do
  pod 'CRJUIComponents', :path => '../'
#  pod 'CRJEdgeInsetsLabel'
  
  target 'CRJUIComponents_Tests' do
    inherit! :search_paths

    
  end
end
